spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_caso_autoservicio
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /solicitudVacaciones